[STC-128] DesktopModal
micromedio/herz-ui pull request #144
Opened 2021-09-09 22:00 UTC by michellehorn

- [x] Modal desktop
- [x] Tests
- [ ] Scroll

2021-09-10 18:38 UTC, giubatt requested changes
Couple of things I couldn't find a line to add the comment so commenting here:
1. As we use yarn we shouldn't have a `package-lock.json` as that could be confusing, better to remove it from the changes
2. The [DesktopModal image snapshot](https://github.com/micromedio/herz-ui/pull/144/files#diff-42f73ba1e1fb7a3b26b18ac7bd3ff05ea70691da499d393061b820d6ffe375a9) is basically an empty image, I think you may need to add it to the `fullPageComponents` array in `Storyshots.test.ts`

2021-09-10 18:38 UTC, giubatt commented on src/components/DesktopModal/DesktopModal.tsx
> +      {...className}
I don't understand this spread, could you explain the reason?

2021-09-10 18:38 UTC, giubatt commented on src/components/DesktopModal/DesktopModal.tsx
> +      <Paper padding={0} sx={{ zIndex: 10, width: widthModal, gap: 5 }}>
I think maybe the className the DesktopModal receives could be added to the paper here (`<Paper className={className} ...etc >`), so there's no need for the widthModal prop, you could just use it like this:
```
<DesktopModal sx={{ width: 500 }}>
  <p>modal body</p>
</DesktopModal>
```

2021-09-10 18:38 UTC, giubatt commented on src/components/DesktopModal/DesktopModal.tsx
> +        </div>
I think we could give more control to the component user if the children wasn't wrapped by this div, what if the use-case needs different paddings or I don't want it to be in a display grid, or the minWidth to be 500?
```suggestion
        {children}
```

2021-09-14 12:37 UTC, giubatt submitted a review, later dismissed

2021-09-14 14:19 UTC, VagnerNico submitted a review, later dismissed

2021-09-14 15:14 UTC, giubatt submitted a review, later dismissed

2021-09-14 15:20 UTC, VagnerNico approved these changes

2021-09-15 17:24 UTC, giubatt submitted a review, later dismissed

2021-09-15 19:00 UTC, giubatt submitted a review, later dismissed

2021-09-15 19:02 UTC, VagnerNico submitted a review, later dismissed

2021-09-17 20:23 UTC, giubatt submitted a review, later dismissed

2021-09-20 17:04 UTC, VagnerNico approved these changes

2021-09-20 17:07 UTC, merged