DEV-74: Update Selector
micromedio/herz-ui pull request #54
Opened 2021-03-22 14:02 UTC by edagonis

Add initialValue and initialSelectedItems props, and add support for react node as option label

2021-03-22 18:03 UTC, welitonderesende requested changes
It would be good to have the docs updated as well since we add a new more complex way of interaction so examples of it are welcomed, like adding an avatar or even an icon.

Also since we strongly advise using react Node only in specific scenarios, I believe those points should be in the documentation as well

2021-03-24 18:27 UTC, welitonderesende approved these changes

2021-03-24 20:17 UTC, giubatt approved these changes

2021-03-26 14:20 UTC, welitonderesende approved these changes

2021-03-26 15:10 UTC, merged